engage_media:
  outputs:
    dev:
      dataset: dbt_{{ env_var('DBT_USER_INITIALS') }}
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: "{{ env_var('DEV_PROJECT_ID') }}"
      threads: 2
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: prod
      fixed_retries: 1
      keyfile: "{{ env_var('PROD_DBT_KEYFILE') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('PROD_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
